[project]
name = "transformer-practice"
version = "0.1.0"
description = "Practice constructing a transformer model using PyTorch"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.0",
    "torch>=2.9.1",
]
